### ISSUE TITLE
failed security requirements

### ISSUE THREAD

**Issue by kofarrell1076** [mmgrt/Tweety#1]
trying to get this to work but when I try and register the web hook we get a failed security requirements. Have everything in place that I can think of so not sure. We just get sent to https://dev.twitter.com/webhooks/securing

any ideas?

**Comment by mmgrt** [comment]
I'll check it today, meanwhile, make sure you have the response requirements in your server as mentioned by Twitter:
_Latency less than 1 second._
_200 HTTP response code._

I usually send a test request by a rest client to make sure the response is OK.

EDIT:
I just checked [@FaceyAI](http://twitter.com/faceyai) bot -hosted in Azure Function- using Tweety NuGet v0.0.18, and it's working with no problems.

**Comment by kofarrell1076** [comment]
Well FaceyAi may be working but we can't get this to work at all and ours is on Azure also. What would be great, for the future,  is a sample project that people can download, get running and then go from there. 

We will have to go with plan b - write our own.
thanks

**Comment by mmgrt** [comment]
I think I found the problem, in the readme file, the docs says that you have to pass your consumer key to the interceptor, while actually, you have to pass the consumer secret, check: [Webhook Interceptor](https://github.com/mmgrt/Tweety/blob/a196c836f74de5db75252f6428bdd53dd4ccbc20/Tweety/Webhooks/WebhookInterceptor.cs#L35)

Can you please confirm that you're using the consumer secret?

**Comment by kofarrell1076** [comment]
I can't confirm if we use consumer secret because we don't use the library an more  I think it could be good, could be useful but your documentation here is very poor. If you want people to use it, you need to take them step by step and not jump from code, to tests , to azure functions. Give them somewhere to start that works (sample webapi code) and you'll get a lot more people using it.

We're writing our own now.
thanks

**Comment by mmgrt** [comment]
Thank you for your comments, will try to find time to improve the docs and provide a get-started guide :)
